### ISSUE TITLE
Todo list V1

### ISSUE THREAD

**Issue by pannneb** [pannneb/NNRecipes#47]
- [ ] Change layout (make it wider and better)
- [ ] Prepare Liquibase scripte
- [ ] Prepare Log-out dialog (remove unneeded buttons)
- [ ] Prepare Initial scripts
- [ ] Add new Recipe - fix form because this option is not working after ReadOnly option was implemented
- [ ] Add create user form without any control
- [ ] Add Recipe's property that determine is recipe visible for all user (public) or private
